apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost
  namespace: argocd
spec:
  project: default
  sources:
    - chart: cost-analyzer
      repoURL: https://kubecost.github.io/cost-analyzer/
      targetRevision: 2.3.1
      helm:
        valueFiles:
          - $values/monitoring/kubecost-values.yaml
    - repoURL: https://github.com/iaminpwd/2nd_team-test2.git # 본인의 실제 Git 주소로 꼭 변경하세요!
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true