apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  ignoreDifferences:
    - group: "apps"
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRole
      jsonPointers:
        - /rules
  sources:
    - chart: cost-analyzer
      repoURL: https://kubecost.github.io/cost-analyzer/
      targetRevision: 2.3.1
      helm:
        valueFiles:
          - $values/monitoring/kubecost/values.yaml
    - repoURL: https://github.com/iaminpwd/2nd_team-test2.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  ignoreDifferences:
    - group: "apps"
      kind: Deployment
      jsonPointers:
        # 1. Deployment 자체의 어노테이션 무시 (이번에 발견한 범인)
        - /metadata/annotations/helm-rollout-restarter
        # 2. 파드 템플릿의 어노테이션 무시
        - /spec/template/metadata/annotations/helm-rollout-restarter
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
